import { Router } from "express";
import { healthRouter } from "../features/health/health.routes.js";
import { adminAuthRouter } from "../features/admin-auth/admin-auth.routes.js";
import { adminDashboardRouter } from "../features/admin-dashboard/admin-dashboard.routes.js";
import { adminPoojaCategoriesRouter } from "../features/admin-pooja-categories/admin-pooja-categories.routes.js";
import { adminPoojasRouter } from "../features/admin-poojas/admin-poojas.routes.js";
import { adminPanditsRouter } from "../features/admin-pandits/admin-pandits.routes.js";
import { adminBookingsRouter } from "../features/admin-bookings/admin-bookings.routes.js";
import { adminCustomersRouter } from "../features/admin-customers/admin-customers.routes.js";
import { adminRolesRouter } from "../features/admin-roles/admin-roles.routes.js";
import { adminAuditLogRouter } from "../features/admin-audit-log/admin-audit-log.routes.js";
import { adminProductCategoriesRouter } from "../features/admin-product-categories/admin-product-categories.routes.js";
import { adminProductsRouter } from "../features/admin-products/admin-products.routes.js";
import { adminBlogCategoriesRouter } from "../features/admin-blog-categories/admin-blog-categories.routes.js";
import { adminBlogsRouter } from "../features/admin-blogs/admin-blogs.routes.js";
import { adminConsultationsRouter } from "../features/admin-consultations/admin-consultations.routes.js";
import { adminFestivalsRouter } from "../features/admin-festivals/admin-festivals.routes.js";
import { adminOrdersRouter } from "../features/admin-orders/admin-orders.routes.js";
import { adminReviewsRouter } from "../features/admin-reviews/admin-reviews.routes.js";
import { adminTestimonialsRouter } from "../features/admin-testimonials/admin-testimonials.routes.js";
import { adminCitiesRouter } from "../features/admin-cities/admin-cities.routes.js";
import { adminCouponsRouter } from "../features/admin-coupons/admin-coupons.routes.js";
import { adminMuhuratsRouter } from "../features/admin-muhurats/admin-muhurats.routes.js";
import { muhuratsRouter } from "../features/muhurats/muhurats.routes.js";
import { poojasRouter } from "../features/poojas/poojas.routes.js";
import { panditsRouter } from "../features/pandits/pandits.routes.js";
import { productsRouter } from "../features/products/products.routes.js";
import { blogsRouter } from "../features/blogs/blogs.routes.js";
import { consultationsRouter } from "../features/consultations/consultations.routes.js";
import { panchangRouter } from "../features/panchang/panchang.routes.js";
import { kundliRouter } from "../features/kundli/kundli.routes.js";
import { festivalsRouter } from "../features/festivals/festivals.routes.js";
import { ordersRouter } from "../features/orders/orders.routes.js";
import { reviewsRouter } from "../features/reviews/reviews.routes.js";
import { testimonialsRouter } from "../features/testimonials/testimonials.routes.js";
import { citiesRouter } from "../features/cities/cities.routes.js";
import { couponsRouter } from "../features/coupons/coupons.routes.js";
import { paymentsRouter } from "../features/payments/payments.routes.js";
import { bookingsRouter } from "../features/bookings/bookings.routes.js";
import { settingsRouter } from "../features/settings/settings.routes.js";
import { adminSettingsRouter } from "../features/admin-settings/admin-settings.routes.js";
import { homepageBannerRouter } from "../features/homepage-banner/homepage-banner.routes.js";
import { adminHomepageBannerRouter } from "../features/admin-homepage-banner/admin-homepage-banner.routes.js";
import { pagesRouter } from "../features/pages/pages.routes.js";
import { adminPagesRouter } from "../features/admin-pages/admin-pages.routes.js";
import { adminMediaRouter } from "../features/admin-media/admin-media.routes.js";
import { seoRouter } from "../features/seo/seo.routes.js";
import { adminSeoRouter } from "../features/admin-seo/admin-seo.routes.js";
import { adminCityPoojaSeoRouter } from "../features/admin-city-pooja-seo/admin-city-pooja-seo.routes.js";
import { adminReportsRouter } from "../features/admin-reports/admin-reports.routes.js";
import { adminNotificationsRouter } from "../features/admin-notifications/admin-notifications.routes.js";
import { adminSearchRouter } from "../features/admin-search/admin-search.routes.js";
import { newsletterRouter } from "../features/newsletter/newsletter.routes.js";
import { adminNewsletterRouter } from "../features/admin-newsletter/admin-newsletter.routes.js";
import { customerAuthRouter } from "../features/customer-auth/customer-auth.routes.js";
import { accountDashboardRouter } from "../features/account-dashboard/account-dashboard.routes.js";
import { accountBookingsRouter } from "../features/account-bookings/account-bookings.routes.js";
import { accountOrdersRouter } from "../features/account-orders/account-orders.routes.js";
import { accountConsultationsRouter } from "../features/account-consultations/account-consultations.routes.js";
import { accountWishlistRouter } from "../features/account-wishlist/account-wishlist.routes.js";
import { accountKundliRouter } from "../features/account-kundli/account-kundli.routes.js";
import { accountAddressesRouter } from "../features/account-addresses/account-addresses.routes.js";
import { accountReviewsRouter } from "../features/account-reviews/account-reviews.routes.js";
import { accountPaymentsRouter } from "../features/account-payments/account-payments.routes.js";
import { accountInvoicesRouter } from "../features/account-invoices/account-invoices.routes.js";
import { accountNotificationsRouter } from "../features/account-notifications/account-notifications.routes.js";
import { accountSupportRouter } from "../features/account-support/account-support.routes.js";
import { accountProfileRouter } from "../features/account-profile/account-profile.routes.js";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);

// Admin Panel API — all protected by requireAdminAuth/requirePermission inside each router.
apiRouter.use("/admin/auth", adminAuthRouter);
apiRouter.use("/admin/dashboard", adminDashboardRouter);
apiRouter.use("/admin/pooja-categories", adminPoojaCategoriesRouter);
apiRouter.use("/admin/poojas", adminPoojasRouter);
apiRouter.use("/admin/pandits", adminPanditsRouter);
apiRouter.use("/admin/bookings", adminBookingsRouter);
apiRouter.use("/admin/customers", adminCustomersRouter);
apiRouter.use("/admin/roles", adminRolesRouter);
apiRouter.use("/admin/audit-logs", adminAuditLogRouter);
apiRouter.use("/admin/product-categories", adminProductCategoriesRouter);
apiRouter.use("/admin/products", adminProductsRouter);
apiRouter.use("/admin/blog-categories", adminBlogCategoriesRouter);
apiRouter.use("/admin/blogs", adminBlogsRouter);
apiRouter.use("/admin/consultations", adminConsultationsRouter);
apiRouter.use("/admin/festivals", adminFestivalsRouter);
apiRouter.use("/admin/orders", adminOrdersRouter);
apiRouter.use("/admin/reviews", adminReviewsRouter);
apiRouter.use("/admin/testimonials", adminTestimonialsRouter);
apiRouter.use("/admin/cities", adminCitiesRouter);
apiRouter.use("/admin/coupons", adminCouponsRouter);
apiRouter.use("/admin/muhurats", adminMuhuratsRouter);
apiRouter.use("/admin/settings", adminSettingsRouter);
apiRouter.use("/admin/cms/homepage-banner", adminHomepageBannerRouter);
apiRouter.use("/admin/cms/pages", adminPagesRouter);
apiRouter.use("/admin/cms/media", adminMediaRouter);
apiRouter.use("/admin/seo", adminSeoRouter);
apiRouter.use("/admin/seo/city-pooja", adminCityPoojaSeoRouter);
apiRouter.use("/admin/reports", adminReportsRouter);
apiRouter.use("/admin/notifications", adminNotificationsRouter);
apiRouter.use("/admin/search", adminSearchRouter);
apiRouter.use("/admin/newsletter-subscribers", adminNewsletterRouter);

// Customer-facing public APIs.
apiRouter.use("/poojas", poojasRouter);
apiRouter.use("/pandits", panditsRouter);
apiRouter.use("/products", productsRouter);
apiRouter.use("/blogs", blogsRouter);
apiRouter.use("/consultations", consultationsRouter);
apiRouter.use("/panchang", panchangRouter);
apiRouter.use("/muhurats", muhuratsRouter);
apiRouter.use("/kundli", kundliRouter);
apiRouter.use("/festivals", festivalsRouter);
apiRouter.use("/orders", ordersRouter);
apiRouter.use("/reviews", reviewsRouter);
apiRouter.use("/testimonials", testimonialsRouter);
apiRouter.use("/cities", citiesRouter);
apiRouter.use("/coupons", couponsRouter);
apiRouter.use("/payments", paymentsRouter);
apiRouter.use("/bookings", bookingsRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/homepage-banner", homepageBannerRouter);
apiRouter.use("/pages", pagesRouter);
apiRouter.use("/seo", seoRouter);
apiRouter.use("/newsletter", newsletterRouter);
apiRouter.use("/customer-auth", customerAuthRouter);

// Customer Account (My Account dashboard) API — all protected by requireCustomerAuth
// inside each router, with ownership checks enforced server-side per resource.
apiRouter.use("/account/dashboard", accountDashboardRouter);
apiRouter.use("/account/bookings", accountBookingsRouter);
apiRouter.use("/account/orders", accountOrdersRouter);
apiRouter.use("/account/consultations", accountConsultationsRouter);
apiRouter.use("/account/wishlist", accountWishlistRouter);
apiRouter.use("/account/kundli", accountKundliRouter);
apiRouter.use("/account/addresses", accountAddressesRouter);
apiRouter.use("/account/reviews", accountReviewsRouter);
apiRouter.use("/account/payments", accountPaymentsRouter);
apiRouter.use("/account/invoices", accountInvoicesRouter);
apiRouter.use("/account/notifications", accountNotificationsRouter);
apiRouter.use("/account/support", accountSupportRouter);
apiRouter.use("/account/profile", accountProfileRouter);
